### ISSUE TITLE
Beat detection problem?

### ISSUE THREAD

**Issue by ghost** [amaljose96/song_to_beat_data#1]
I am using your whole project thru song_to_beat_data to chord_detector. The problem im facing is that i set song that has 192 beats as an input, but the output says 

'''Wrote beat 257 with 80 frames and 10240 columns

258 rows. '''

I guess 258 rows means 258beats. Guess it has problem detecting the beat. The song I used is 11.mp3 and the output is 11_data.txt(I'll attach the files as a zip file.)
[11.zip](https://github.com/amaljose96/song_to_beat_data/files/3207250/11.zip)
 I hope you know the answer.

**Comment by amaljose96** [comment]
Hi @hajaejung . I guess one of the following might be the reasons for the beat mismatch:
1. The beat detector uses tempo from aubio for detecting if there is a beat in that sample or not.
So I guess the beginning part (without the drums) was skipped since the beat detector couldn't sense the beats there. 
2. The song you've given has a tempo of 174bpm.
The song_to_beat_data takes the first 0.232s of every beat as the beat's data, for detecting chords (10240/44100). Reason why this was done was to keep the number of columns for a beat consistent across tempos (eg. a song at 120bpm would have 0.5s for a beat ie. 22,050 samples and a song at 80bpm would have 0.75s for a beat ie. 33,075 samples).
Because of this limit of 10240 samples for a beat, the max tempo that can be accomodated is 258bpm.

As its just the first step, it works on jazz, pop and simpler songs.
Hoping to accomodate other genres too.

Hope that has solved your query.
